### ISSUE TITLE
Don't works on Firefox

### ISSUE THREAD

**Issue by SimonLeclere** [Darkempire78/StackOverflow-Snippets#1]
![image](https://user-images.githubusercontent.com/39917969/166520189-5d7822c5-5be6-459f-a007-f2ffb9479064.png)

**Comment by Darkempire78** [comment]
Yes, there is an issue on Firefox (check the console), but it works on Chrome.
Idk how to fix this for the moment... :/

**Comment by SimonLeclere** [comment]
If I have time I will try to look for it ;)

**Comment by Darkempire78** [comment]
It must be fixed
